# Core Constants defining EMIOS simulation modifiers and agent thresholds

# In-Memory DB Config
DEFAULT_MIGRATION_STATUS = "Legacy"

# Cascading Risk Criticality Multipliers
CRITICALITY_FACTOR_HIGH = 0.8
CRITICALITY_FACTOR_MEDIUM = 0.4
CRITICALITY_FACTOR_LOW = 0.1

# Connection Type Modifiers
TYPE_MODIFIER_SYNC = 1.2
TYPE_MODIFIER_DB = 1.1
TYPE_MODIFIER_ASYNC_MQ = 0.5

# Monte Carlo Range Boundaries
MONTE_CARLO_MIN_DURATION_FACTOR = 0.9
MONTE_CARLO_MAX_DURATION_BASE = 1.1
MONTE_CARLO_MAX_DURATION_RISK_MULTIPLIER = 2.0

MONTE_CARLO_MIN_COST_FACTOR = 0.95
MONTE_CARLO_MAX_COST_BASE = 1.2
MONTE_CARLO_MAX_COST_RISK_MULTIPLIER = 2.5

# Multi-Agent Planner Thresholds
PLANNER_MAX_ITERATIONS = 5
PLANNER_RISK_THRESHOLD = 0.15  # Objections trigger if a node risk exceeds 15%
PLANNER_VIOLATION_COST_HIGH = 0.40
PLANNER_VIOLATION_COST_MEDIUM = 0.20
PLANNER_VIOLATION_COST_SYNC = 0.15

# Estimator Defaults
MIGRATION_COST_FACTOR = 1.2
MIGRATION_COST_MIN = 5000.0
REVENUE_MULTIPLIER = 10.0
MONTHS_IN_YEAR = 12.0
MIGRATION_DURATION_LOW = 14
MIGRATION_DURATION_MEDIUM = 30
MIGRATION_DURATION_HIGH = 90
CLOUD_SAVINGS_MULTIPLIER = 0.30
