"""add unique constraint on report_revisions report_id version

Revision ID: 41d873c2dac6
Revises: 8e2ec83b5c75
Create Date: 2026-07-31 14:21:29.852457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d873c2dac6'
down_revision: Union[str, Sequence[str], None] = '8e2ec83b5c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_report_revision_report_version', 'report_revisions', ['report_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_report_revision_report_version', 'report_revisions', type_='unique')
    # ### end Alembic commands ###
