"""baseline schema

Revision ID: 8e2ec83b5c75
Revises: 
Create Date: 2026-07-30 16:43:45.769676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2ec83b5c75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('target_cloud', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_created_by'), 'assessments', ['created_by'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('final_result', sa.JSON(), nullable=True),
    sa.Column('pipeline_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_assessment_id'), 'agent_runs', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_batch_id'), 'agent_runs', ['batch_id'], unique=False)
    op.create_table('assessment_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('is_discovered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_edges_assessment_id'), 'assessment_edges', ['assessment_id'], unique=False)
    op.create_table('assessment_nodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('business_value', sa.String(length=32), nullable=False),
    sa.Column('revenue_impact', sa.Float(), nullable=False),
    sa.Column('migration_complexity', sa.String(length=32), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('base_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('runtime', sa.String(length=64), nullable=True),
    sa.Column('annual_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_nodes_assessment_id'), 'assessment_nodes', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_nodes_node_id'), 'assessment_nodes', ['node_id'], unique=False)
    op.create_table('assessment_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('risk_summary', sa.JSON(), nullable=True),
    sa.Column('migration_waves', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feedback_rating', sa.String(length=16), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_migration_plan', sa.JSON(), nullable=True),
    sa.Column('final_plan_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_reports_assessment_id'), 'assessment_reports', ['assessment_id'], unique=True)
    op.create_table('assessment_simulations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('already_migrated', sa.JSON(), nullable=False),
    sa.Column('impacted_services', sa.JSON(), nullable=False),
    sa.Column('critical_paths', sa.JSON(), nullable=False),
    sa.Column('monte_carlo', sa.JSON(), nullable=True),
    sa.Column('revenue_at_risk', sa.Float(), nullable=False),
    sa.Column('total_hosting_cost', sa.Float(), nullable=False),
    sa.Column('potential_savings', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_simulations_assessment_id'), 'assessment_simulations', ['assessment_id'], unique=True)
    op.create_table('assessment_uploads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_uploads_assessment_id'), 'assessment_uploads', ['assessment_id'], unique=False)
    op.create_table('migration_waves',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'wave_number', name='uq_migration_wave_assessment_number')
    )
    op.create_index(op.f('ix_migration_waves_assessment_id'), 'migration_waves', ['assessment_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['assessment_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_assessment_id'), 'document_chunks', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_qdrant_point_id'), 'document_chunks', ['qdrant_point_id'], unique=True)
    op.create_index(op.f('ix_document_chunks_upload_id'), 'document_chunks', ['upload_id'], unique=False)
    op.create_table('report_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('risk_summary', sa.JSON(), nullable=True),
    sa.Column('migration_waves', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('changed_sections', sa.JSON(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['assessment_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_revisions_report_id'), 'report_revisions', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_revisions_report_id'), table_name='report_revisions')
    op.drop_table('report_revisions')
    op.drop_index(op.f('ix_document_chunks_upload_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_qdrant_point_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_assessment_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_migration_waves_assessment_id'), table_name='migration_waves')
    op.drop_table('migration_waves')
    op.drop_index(op.f('ix_assessment_uploads_assessment_id'), table_name='assessment_uploads')
    op.drop_table('assessment_uploads')
    op.drop_index(op.f('ix_assessment_simulations_assessment_id'), table_name='assessment_simulations')
    op.drop_table('assessment_simulations')
    op.drop_index(op.f('ix_assessment_reports_assessment_id'), table_name='assessment_reports')
    op.drop_table('assessment_reports')
    op.drop_index(op.f('ix_assessment_nodes_node_id'), table_name='assessment_nodes')
    op.drop_index(op.f('ix_assessment_nodes_assessment_id'), table_name='assessment_nodes')
    op.drop_table('assessment_nodes')
    op.drop_index(op.f('ix_assessment_edges_assessment_id'), table_name='assessment_edges')
    op.drop_table('assessment_edges')
    op.drop_index(op.f('ix_agent_runs_batch_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_assessment_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_assessments_created_by'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
